name: Run tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-21.04
    container: alperbayram/computational-workflows
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          python3 -m pytest
